export default [
'Aero & Astro',
'CmpMfg&SimCt',
'CnstrMgmtTch',
'COE PerfSpac',
'ComputerGrph',
'Cpt&InfoTech',
'Divrsty&Incl',
'Divrsty Rsrc',
'Gen Acad Cls',
'Gen Building',
'Elec&CptEngr',
'Eng Cpt Ntwk',
'Eng Prof Ed',
'Engineering',
'Engr BO',
'Engr Educ',
'Engr Tech',
'EPICS',
'Future Engnr',
'Global Engr',
'Indust Engr',
'Matl Engr',
'MinorityEngr',
'Ntwk Cmp Nan',
'Nucl Engr',
'Oper & Maint',
'Polytechnic',
'PRF Devlpmnt',
'Prf Std Tech',
'PUDiningCatr',
'Purdue Bound',
'Spns Pgm Srv',
'Univ Rsv Ac',
'VP Research',
'Women Engr',
]
